version: '3'
 
#networks:
#  prodnetwork:
#    driver: bridge
 
services:
 #newman:
 # image: postman/newman_ubuntu1404
 # ports:
  #  - "91:80"
  #networks:
   # - prodnetwork
  #depends_on:
   # - jenkins

 jenkins:
  image: jenkins/jenkins:lts
  ports:
    - "28080:8080"
#  networks:
#    - prodnetwork
  container_name: container-jenkins  

 
