version: '3'
 
#networks:
#  prodnetwork:
#    driver: bridge
 
services:
 #newman:
 # image: postman/newman_ubuntu1404
 # ports:
  #  - "91:80"
  #networks:
   # - prodnetwork
  #depends_on:
   # - jenkins

 jenkins:
  image: jenkins/jenkins:lts
  ports:
    - "28080:8080"
#  networks:
#    - prodnetwork
  container_name: container-jenkins  
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /usr/local/bin/docker:/usr/bin/docker
    - /opt/jenkins/:/var/lib/jenkins/
  depends_on:
    - gitlab
 
 gitlab:
  image: gitlab/gitlab-ce
  restart: always
#  networks:
#    - prodnetwork
  environment:
    GITLAB_OMNIBUS_CONFIG: |
      # external_url 'https://gitlab.example.com'
      # Add any other gitlab.rb configuration here, each on its own line
  ports:
    - "90:80"
    - "443:443"
    - "2222:22"
  container_name: container-gitlab  
  volumes:
    - /opt/gitlab/config:/etc/gitlab
    - /opt/gitlab/logs:/var/log/gitlab
    - /opt/gitlab/data:/var/opt/gitlab
